config/routes.rb
Rails.application.routes.draw do
  root to: 'top#home'
  post 'top' => 'top#index'
  get 'top' => 'top#show'

  get 'flashcard/top'
  get 'flashcard/play'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/word.rb
class Word < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flashcard_controller.rb
class FlashcardController < ApplicationController
  
  def top
  end

  def play
    num = rand(Word.count)
    @word = Word.offset(num).first
    logger.debug(@word.inspect)
    respond_to do |format|
      format.html
      format.json {render json: @word}
    end
  end
  
end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def home
    
  end
  
  def index
    unknownWord = params[:word]
    agent = Mechanize.new
    page = agent.get("https://ejje.weblio.jp/content/#{unknownWord}")
    title = page.search('#h1Query').inner_text
    meaning = page.search('.content-explanation').inner_text
    @word = Word.new
    @word.title = title
    @word.meaning = meaning
    @word.save
    redirect_to "/top"
  end

  def show
    @words = Word.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashcard_helper.rb
module FlashcardHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/flashcard/_card.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>単語帳画面</title>
</head>
<body>
  <div id="card">
    <div id="card-front">
      <p><%= @word.title %></p>
    </div>
    <div id="card-back">
      <p><%= @word.meaning %></p>
    </div>
  </div>
  <%= javascript_pack_tag 'test' %>
</body>
</html>
  

app/views/flashcard/play.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>JSDemo2</title>

</head>
<body id="flashcard-play">
  <%= render 'card' %>
  <div id="btn">
    NEXT
  </div>

</body>
</html>

app/views/flashcard/play.js.erb
$('#flashcard-play').html("<%= j(render 'card') %>")

app/views/flashcard/top.html.erb
<h1>単語帳ホーム</h1>

<%= link_to "スタート", flashcard_play_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/home.html.erb
<h1>Top#home</h1>

<%= form_with url: top_path, method: :post, local: true do |form| %>
 <%= form.text_field :word %>
 <%= form.submit '投稿する' %>
<% end %>

<%= link_to "単語帳", flashcard_top_path %>

app/views/top/show.html.erb
<body id="word-table">
<h1>Top#show</h1>

<table border= "1">
    <thead>
        <tr class="thead">
            <th>word</th>
            <th>meaning</th>
        </tr>
    </thead>
    <tbody class="tbody">
      <% @words.each do |word| %>
        <tr>
          <td><%= word.title %></td>
          <td><%= word.meaning %></td>
        </tr>
      <% end %>
    </tbody>
</table>
</body>